spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/data/db
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    src: info
  file:
    path: ./logs