spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/data/db
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    com.example.jpa: INFO
  file:
    path: ./logs